#!/usr/bin/env python3
"""Generate THIRD_PARTY_LICENSES.txt.

Walks the installed distributions in the current environment, drops the
dev/build-only tooling that is not shipped in MizMap binaries, and emits an
aggregated notice file carrying each bundled dependency's license text, plus
manual entries for components that are not pip distributions (vendored AGPL
protos, the embedded CPython runtime, the PyInstaller bootloader, and the
CDN-loaded frontend libraries).

Re-run after changing dependencies, using the project venv interpreter:

    .venv/Scripts/python.exe scripts/gen_third_party_licenses.py   (Windows)
    .venv/bin/python scripts/gen_third_party_licenses.py           (macOS/Linux)
"""

from __future__ import annotations

import re
from importlib import metadata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD_PARTY_LICENSES.txt"

# Present in the dev environment but NOT bundled into the shipped binary:
# test, lint, and the PyInstaller build chain. Normalized (lowercase, dashes).
DEV_BUILD_ONLY = {
    "mizmap",
    "pytest",
    "pytest-asyncio",
    "iniconfig",
    "pluggy",
    "ruff",
    "pyinstaller",
    "pyinstaller-hooks-contrib",
    "altgraph",
    "pefile",
    "pywin32-ctypes",
    "grpcio-tools",
    "hatchling",
    "setuptools",
    "pip",
    "wheel",
    "tomli",
}

SEP = "=" * 78
LICENSE_FILE_RE = re.compile(r"(?i)(licen[sc]e|copying|notice)")


def norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def license_id(md: metadata.PackageMetadata) -> str:
    expr = md.get("License-Expression")
    if expr:
        return expr
    classifiers = [
        c.split("::")[-1].strip()
        for c in md.get_all("Classifier") or []
        if c.startswith("License ::")
    ]
    if classifiers:
        return ", ".join(classifiers)
    lic = md.get("License")
    if lic and "\n" not in lic and len(lic) <= 80:
        return lic
    return "(see text below)"


def homepage(md: metadata.PackageMetadata) -> str:
    home = md.get("Home-page")
    if home:
        return home
    for url in md.get_all("Project-URL") or []:
        return url.split(",", 1)[-1].strip()
    return ""


def license_texts(dist: metadata.Distribution) -> dict[str, str]:
    out: dict[str, str] = {}
    for f in dist.files or []:
        s = str(f).replace("\\", "/")
        if ".dist-info/" not in s:
            continue
        base = Path(s).name
        if not LICENSE_FILE_RE.search(base):
            continue
        try:
            out[base] = dist.locate_file(f).read_text(encoding="utf-8", errors="replace")
        except (OSError, UnicodeError):
            pass
    return out


def collect() -> list[metadata.Distribution]:
    dists: list[metadata.Distribution] = []
    seen: set[str] = set()
    for dist in metadata.distributions():
        name = dist.metadata["Name"]
        if not name:
            continue
        key = norm(name)
        if key in DEV_BUILD_ONLY or key in seen:
            continue
        seen.add(key)
        dists.append(dist)
    dists.sort(key=lambda d: norm(d.metadata["Name"]))
    return dists


def main() -> None:
    dists = collect()
    parts: list[str] = [
        "THIRD-PARTY SOFTWARE NOTICES AND LICENSES",
        "",
        "MizMap is licensed under the GNU General Public License v3.0 or later;\n"
        "see the LICENSE file. The binary distributions of MizMap (the Windows\n"
        "installer and the PyInstaller bundle) include the third-party components\n"
        "listed below, each under its own license. This file is generated by\n"
        "scripts/gen_third_party_licenses.py -- do not edit it by hand.",
        "",
    ]

    for dist in dists:
        md = dist.metadata
        parts.append(SEP)
        parts.append(f"{md['Name']} {md['Version'] or ''}".strip())
        parts.append(f"License: {license_id(md)}")
        home = homepage(md)
        if home:
            parts.append(f"Homepage: {home}")
        parts.append("")
        texts = license_texts(dist)
        if texts:
            for fname, text in texts.items():
                parts.append(f"--- {fname} ---")
                parts.append(text.rstrip("\n"))
                parts.append("")
        else:
            parts.append(
                "(No license file is shipped in this package's metadata; see the "
                "package homepage for the full license terms.)"
            )
            parts.append("")

    parts += [
        SEP,
        "DCS-gRPC protobuf definitions (vendored: proto/ and mizmap/proto_gen/)",
        "License: AGPL-3.0-only",
        "Homepage: https://github.com/DCS-gRPC/rust-server",
        "",
        "The .proto interface files under proto/ and the Python stubs generated\n"
        "from them under mizmap/proto_gen/ are derived from the DCS-gRPC\n"
        "rust-server project and remain under the GNU Affero General Public\n"
        "License v3.0. GPL-3.0 section 13 expressly permits combining a GPLv3\n"
        "work with AGPLv3 material. The full text is in LICENSES/AGPL-3.0.txt.",
        "",
        SEP,
        "CPython runtime and standard library (embedded by PyInstaller)",
        "License: PSF-2.0",
        "Homepage: https://www.python.org",
        "",
        "Frozen MizMap binaries embed a copy of the CPython interpreter and its\n"
        "standard library, distributed under the Python Software Foundation\n"
        "License. Full text: https://docs.python.org/3/license.html",
        "",
        SEP,
        "PyInstaller bootloader (compiled into the frozen executable)",
        "License: GPL-2.0-or-later WITH Bootloader-exception",
        "Homepage: https://pyinstaller.org",
        "",
        "The PyInstaller bootloader carries a GPL exception that explicitly\n"
        "permits its use in applications under any license. Full text:\n"
        "https://github.com/pyinstaller/pyinstaller/blob/master/COPYING.txt",
        "",
        SEP,
        "Frontend libraries and map data",
        "(loaded at runtime from a CDN / tile server; not redistributed in the binary)",
        "",
        "- Leaflet -- BSD-2-Clause -- https://leafletjs.com\n"
        "- milsymbol -- MIT -- https://github.com/spatialillusions/milsymbol\n"
        "- Map tiles: OpenTopoMap (CC-BY-SA 3.0) -- https://opentopomap.org\n"
        "- Map data: (C) OpenStreetMap contributors (ODbL 1.0) --\n"
        "  https://www.openstreetmap.org/copyright",
        "",
    ]

    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(dists)} bundled distributions + 5 manual entries).")


if __name__ == "__main__":
    main()
